source 'https://rubygems.org'

gem 'puma', '~> 3.11'
gem 'sidekiq', '~> 5.1'
gem 'sinatra', '~> 2.0'

gem 'haml', '~> 5.0', '>= 5.0.4'
gem 'sass', '~> 3.5', '>= 3.5.6'
gem 'uglifier', '~> 4.1', '>= 4.1.9'
gem 'sprockets', '~> 3.7', '>= 3.7.1'
