run:
	java -cp target:vendor/commons-lang3-3.7.jar c9.App

build:
	javac -d target -cp vendor/commons-lang3-3.7.jar src/*.java

package:
	wget -P vendor http://central.maven.org/maven2/org/apache/commons/commons-lang3/3.7/commons-lang3-3.7.jar
