kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}-server
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.container.port }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.container.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-server
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-server
    spec:
      containers:
        - name: {{ .Release.Name }}-server
          image: {{ .Values.container.image }}
          ports:
            - containerPort: {{ .Values.container.port }}
          args: ['-text', 'OK', '-listen', ':{{ .Values.container.port }}']
