version: '3.9'
services:
  terraform:
    working_dir: /envs
    volumes:
      - ./envs:/envs
      - ./modules:/modules
    image: hashicorp/terraform:0.14.10
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
