version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: infra/Dockerfile
    ports:
      - 4567:4567
    volumes:
      - ./app:/src
    command: ruby /src/api/api.rb -o 0.0.0.0
  redis:
    ports:
      - 6379:6379
    image: redis:alpine
