version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: infra/Dockerfile
    ports:
      - 4567:4567
    volumes:
      - ./app:/src
    command: bundle exec puma -p 4567
  redis:
    ports:
      - 6379:6379
    image: redis:alpine
