version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: infra/Dockerfile
    volumes:
      - ./app:/src
    command: bundle exec puma -p 9001
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  nginx:
    image: nginx:1.24-alpine
    ports:
      - 9000:80
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
