services:
  app:
    build:
      context: .
      dockerfile: infra/Dockerfile
    volumes:
      - ./app:/src
    command: bundle exec puma -p 9001

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_dev_data:/data

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.24-alpine
    ports:
      - 443:443
    volumes:
      - ./infra/nginx/certs/dev.crt:/ssl/dev.crt
      - ./infra/nginx/certs/dev.key:/ssl/dev.key
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  redis_dev_data:
  postgres_dev_data:
