name             'base-cookbook'
version          '1.0.0'
license          'Apache'
maintainer       'Alex Y'
maintainer_email 'none@gmail.com'
description      'Base cookbook 1.0'
long_description 'Base cookbook 1.0'
source_url       'https://github.com/chef-cookbooks/base-cookbook'
issues_url       'https://github.com/chef-cookbooks/base-cookbook/issues'

depends 'apt'
depends 'java'
depends 'sudo'
depends 'nginx'
depends 'logrotate'
